package com.learning.dashboardmobileapp.core.ui

object UiConstants {
    // Auth & Login
    const val APP_NAME = "Learning Dashboard"
    const val APP_TAGLINE = "Learn. Track. Grow."
    const val LOGO_CONTENT_DESC = "Learning Dashboard Logo"
    const val EMAIL_LABEL = "Email"
    const val EMAIL_PLACEHOLDER = "learner@example.com"
    const val PASSWORD_LABEL = "Password"
    const val PASSWORD_PLACEHOLDER = "••••••••••••"
    const val SHOW_PASSWORD_DESC = "Show password"
    const val HIDE_PASSWORD_DESC = "Hide password"
    const val LOGIN_BUTTON_TEXT = "Login"
    const val DEMO_ACCOUNT_TITLE = "DEMO ACCOUNT"
    const val AUTO_FILL_BUTTON_TEXT = "Auto-fill"
    const val DEMO_EMAIL_LABEL = "Email:"
    const val DEMO_PASSWORD_LABEL = "Password:"
    const val DEMO_EMAIL_VALUE = "learner@example.com"
    const val DEMO_PASSWORD_VALUE = "password123"

    // Dashboard
    const val GREETING_TEXT = "Good Morning"
    const val GREETING_EMOJI = "👋"
    const val DASHBOARD_SUBTITLE = "Keep learning and make progress today."
    const val STUDENT_PROFILE_DESC = "Student Profile"
    const val LOGOUT_DESC = "Log out"
    const val PREVIEW_MODE_NORMAL = "Normal"
    const val PREVIEW_MODE_SKELETON = "Skeleton"
    const val PREVIEW_MODE_EMPTY = "Empty"
    const val PREVIEW_MODE_ERROR = "Error"
    const val ACTIVE_CURRICULUM_TITLE = "ACTIVE CURRICULUM"
    const val YOUR_LEARNING_TITLE = "Your Learning"
    const val MY_COURSES_TITLE = "My Courses"
    const val SORTED_BY_RECENT = "Sorted by Recent"
    const val NETWORK_CONNECTION_FAILED = "Network connection failed. Unable to fetch courses."
    const val INSTRUCTOR_PREFIX = "Instructor : "
    const val OFFLINE_READY_BADGE = "Offline ready"
    const val CACHED_INDICATOR = "cached"
    const val CONTINUE_BUTTON_TEXT = "Continue"
    const val LESSONS_SUFFIX = "Lessons"
    const val LESSONS_COMPLETED_SUFFIX = "lessons completed"
    const val COURSES_ENROLLED_SUFFIX = "Courses enrolled"

    // Course Details
    const val COURSE_OVERVIEW_TITLE = "Course Overview"
    const val BACK_BUTTON_DESC = "Back"
    const val SYNCED_BADGE = "Synced"
    const val ONLINE_BADGE = "Online"
    const val CERTIFIED_BADGE = "Certified"
    const val INSTRUCTOR_DETAIL_PREFIX = "Instructor: "
    const val ON_TRACK_BADGE = "On Track"
    const val TOTAL_TIME_LABEL = "Total Time"
    const val HOURS_SUFFIX = "hrs"
    const val DOWNLOADED_LABEL = "Downloaded"
    const val QUIZ_SCORE_LABEL = "Quiz Score"
    const val LESSONS_SECTION_TITLE = "Lessons"
    const val LISTED_SUFFIX = "Listed"
    const val MODULE_INFO = "Module 1 of 4"
    const val DOWNLOADED_CONTENT_TITLE = "Downloaded Course Content"
    const val MARK_AS_COMPLETED_BUTTON = "Mark as Completed"
    const val LESSON_COMPLETED_BANNER = "Lesson Completed"
    const val COURSE_NOT_FOUND = "Course not found"
    const val MINS_SEPARATOR = "mins • "

    // Common Components & Statuses
    const val STATUS_SYNCED_READY = "Synced & Ready offline"
    const val STATUS_OFFLINE_MODE = "Offline Mode"
    const val BUTTON_ONLINE_MODE = "Online Mode"
    const val BUTTON_SIMULATE_OFFLINE = "Simulate Offline"
    const val PROGRESS_LABEL = "Progress"
    const val STATUS_COMPLETED = "Completed"
    const val STATUS_PENDING = "Pending"
    const val SOMETHING_WENT_WRONG = "Something went wrong"
    const val RETRY_BUTTON = "Retry"
    const val NO_COURSES_AVAILABLE = "No Courses Available"
    const val EMPTY_COURSES_DESCRIPTION = "You haven't enrolled in any courses yet or the cache is empty."
    const val REFRESH_BUTTON = "Refresh"
}
